GET http://localhost:3000/envios/pendientes

###
POST http://localhost:3000/envios
Content-Type: application/json

{
    "destino": "MDZ",
    "email": "alejandro_mattias@gmail.com"
}

###
PUT http://localhost:3000/envios/01/entregado

###
GET http://localhost:3000/envio/01
