GET http://localhost:3000/envios/pendientes

###
POST http://localhost:3000/envios
Content-Type: application/json

{
    "destino": "Las Heras",
    "email": "alejandro_mattias@gmail.com"
}

###
PUT http://localhost:3000/envios/iavgdh45/entregado

###
GET http://localhost:3000/envio/iavgdh45