AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API de Envios

Resources:
  Productos:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      Events:
        ListEnvios:
          Type: Api
          Properties:
            Path: /envios/pendientes
            Method: get
        CreateEnvio:
          Type: Api
          Properties:
            Path: /envios
            Method: post
        GetOneEnvio:
          Type: Api
          Properties:
            Path: /envios/{id}
            Method: get
        ShipEnvio:
          Type: Api
          Properties:
            Path: /envios/{id}/entregado
            Method: put